import type { FieldConfig } from "@/types/contact/formFields";
import { z } from "zod";

// * ------------------------------------------------------------------
// * AUTO-GENERATED BY scripts/sync-schema.ts
// * ------------------------------------------------------------------

// * Options definitions
const paidPilotOptions = [
  {
    "value": "❌ No — we only test free",
    "label": "❌ No — we only test free"
  },
  {
    "value": "⚠️ Depends on price",
    "label": "⚠️ Depends on price"
  },
  {
    "value": "✅ Yes — paid pilot is fine",
    "label": "✅ Yes — paid pilot is fine"
  },
  {
    "value": "Yes",
    "label": "Yes"
  }
];

const businessTypeOptions = [
  {
    "value": "🏘️Real Estate",
    "label": "🏘️Real Estate"
  },
  {
    "value": "💼 B2B  Niche",
    "label": "💼 B2B  Niche"
  },
  {
    "value": "💹Marketplace",
    "label": "💹Marketplace"
  },
  {
    "value": "🛠️ Contractor / Home Service",
    "label": "🛠️ Contractor / Home Service"
  },
  {
    "value": "🧪 Herbal / Botanical Niche",
    "label": "🧪 Herbal / Botanical Niche"
  },
  {
    "value": "🎤 Event & Creative Niche",
    "label": "🎤 Event & Creative Niche"
  },
  {
    "value": "🙌🏽Coaching Niche",
    "label": "🙌🏽Coaching Niche"
  },
  {
    "value": "🧑‍💻 Tech & SaaS Niche",
    "label": "🧑‍💻 Tech & SaaS Niche"
  },
  {
    "value": "🛍️ E-commerce & Retail",
    "label": "🛍️ E-commerce & Retail"
  },
  {
    "value": "🧘 Health / Wellness",
    "label": "🧘 Health / Wellness"
  },
  {
    "value": "🧾 Professional Services",
    "label": "🧾 Professional Services"
  },
  {
    "value": "🌱 Alternative / Mission-Driven",
    "label": "🌱 Alternative / Mission-Driven"
  },
  {
    "value": "♎ B2C High Virality",
    "label": "♎ B2C High Virality"
  },
  {
    "value": "🔧 Misc. Flexible Options",
    "label": "🔧 Misc. Flexible Options"
  },
  {
    "value": "Agency",
    "label": "Agency"
  },
  {
    "value": "SaaS",
    "label": "SaaS"
  }
];

const crmConnectionOptions = [
  {
    "value": "Yes i dont want to manually upload leads",
    "label": "Yes i dont want to manually upload leads"
  },
  {
    "value": "No id rather manually upload the generated leads",
    "label": "No id rather manually upload the generated leads"
  },
  {
    "value": "Yes",
    "label": "Yes"
  }
];

const existingLeadListsOptions = [
  {
    "value": "Yes — Clean",
    "label": "Yes — Clean"
  },
  {
    "value": "Yes — Messy",
    "label": "Yes — Messy"
  },
  {
    "value": "No",
    "label": "No"
  },
  {
    "value": "Yes",
    "label": "Yes"
  }
];

const icpCategoryOptions = [
  {
    "value": "Real Estate Agencies",
    "label": "Real Estate Agencies"
  },
  {
    "value": "Residential Real Estate Agents",
    "label": "Residential Real Estate Agents"
  },
  {
    "value": "Commercial Real Estate Agents",
    "label": "Commercial Real Estate Agents"
  },
  {
    "value": "Residential Real Estate Brokers",
    "label": "Residential Real Estate Brokers"
  },
  {
    "value": "Commercial Real Estate Brokers",
    "label": "Commercial Real Estate Brokers"
  },
  {
    "value": "Commercial Real Estate Investors",
    "label": "Commercial Real Estate Investors"
  },
  {
    "value": "Residential Real Estate Investors",
    "label": "Residential Real Estate Investors"
  },
  {
    "value": "Residential Real Estate Wholesalers",
    "label": "Residential Real Estate Wholesalers"
  },
  {
    "value": "Commercial Real Estate Wholesalers",
    "label": "Commercial Real Estate Wholesalers"
  },
  {
    "value": "SaaS Founders",
    "label": "SaaS Founders"
  },
  {
    "value": "Tech Startups",
    "label": "Tech Startups"
  },
  {
    "value": "B2B Service Providers",
    "label": "B2B Service Providers"
  },
  {
    "value": "Local Business Owners",
    "label": "Local Business Owners"
  },
  {
    "value": "E-commerce Brands",
    "label": "E-commerce Brands"
  },
  {
    "value": "Consultant / Coachs",
    "label": "Consultant / Coachs"
  },
  {
    "value": "Solopreneurs",
    "label": "Solopreneurs"
  },
  {
    "value": "Construction / Contractors",
    "label": "Construction / Contractors"
  },
  {
    "value": "Home Services (HVAC Plumbing Roofing etc.)",
    "label": "Home Services (HVAC Plumbing Roofing etc.)"
  },
  {
    "value": "Marketing Agency",
    "label": "Marketing Agency"
  },
  {
    "value": "Freelancer",
    "label": "Freelancer"
  },
  {
    "value": "Nonprofit / Community Org",
    "label": "Nonprofit / Community Org"
  },
  {
    "value": "Event Curator / Event Organizer",
    "label": "Event Curator / Event Organizer"
  },
  {
    "value": "Herbalist / Botanical Products",
    "label": "Herbalist / Botanical Products"
  },
  {
    "value": "Dating App Users",
    "label": "Dating App Users"
  },
  {
    "value": "Consumers with inherent virality",
    "label": "Consumers with inherent virality"
  },
  {
    "value": "Other",
    "label": "Other"
  },
  {
    "value": "B2B",
    "label": "B2B"
  }
];

const speedOptions = [
  {
    "value": "⏱ Not sure / depends",
    "label": "⏱ Not sure / depends"
  },
  {
    "value": "⏱ 2–4 weeks",
    "label": "⏱ 2–4 weeks"
  },
  {
    "value": "⏱ Within 7–10 business days",
    "label": "⏱ Within 7–10 business days"
  },
  {
    "value": "⏱ Within 3–5 business days",
    "label": "⏱ Within 3–5 business days"
  },
  {
    "value": "Immediately",
    "label": "Immediately"
  }
];

const interestedFeaturesOptions = [
  {
    "value": "Look-A-like Audinece Generation (Find leads similar to your top closed clients)",
    "label": "Look-A-like Audinece Generation (Find leads similar to your top closed clients)"
  },
  {
    "value": "Lead Enrichment - Find Phone numbers emails and socials of leads.",
    "label": "Lead Enrichment - Find Phone numbers emails and socials of leads."
  },
  {
    "value": "Automated Outreach Text/Call/Linkedin-Instagram-Facebook  (Deal Scale)",
    "label": "Automated Outreach Text/Call/Linkedin-Instagram-Facebook  (Deal Scale)"
  },
  {
    "value": "Search Engine Optimization (Get Discovered On Search Engines)",
    "label": "Search Engine Optimization (Get Discovered On Search Engines)"
  },
  {
    "value": "AI  Engine Optimization (Get suggested by AI)",
    "label": "AI  Engine Optimization (Get suggested by AI)"
  },
  {
    "value": "Lead Enrichment",
    "label": "Lead Enrichment"
  }
];

const painPointsOptions = [
  {
    "value": "Not enough high-quality leads",
    "label": "Not enough high-quality leads"
  },
  {
    "value": "Hard to find high-intent leads",
    "label": "Hard to find high-intent leads"
  },
  {
    "value": "Don't know which websites to scrape",
    "label": "Don't know which websites to scrape"
  },
  {
    "value": "Lead lists are outdated",
    "label": "Lead lists are outdated"
  },
  {
    "value": "Lead lists are incomplete",
    "label": "Lead lists are incomplete"
  },
  {
    "value": "Missing phone numbers",
    "label": "Missing phone numbers"
  },
  {
    "value": "Missing emails",
    "label": "Missing emails"
  },
  {
    "value": "Missing social profiles",
    "label": "Missing social profiles"
  },
  {
    "value": "Data is messy or inconsistent",
    "label": "Data is messy or inconsistent"
  },
  {
    "value": "Need accurate contact information",
    "label": "Need accurate contact information"
  },
  {
    "value": "Need verified leads only",
    "label": "Need verified leads only"
  },
  {
    "value": "Need more targeted prospects",
    "label": "Need more targeted prospects"
  },
  {
    "value": "Hard to identify ideal customers",
    "label": "Hard to identify ideal customers"
  },
  {
    "value": "Need lookalike audience generation",
    "label": "Need lookalike audience generation"
  },
  {
    "value": "Need lead scoring or ranking",
    "label": "Need lead scoring or ranking"
  },
  {
    "value": "Leads are scattered across too many places",
    "label": "Leads are scattered across too many places"
  },
  {
    "value": "Need centralized lead database",
    "label": "Need centralized lead database"
  },
  {
    "value": "Want automated recurring scraping",
    "label": "Want automated recurring scraping"
  },
  {
    "value": "Need bulk enrichment for large lists",
    "label": "Need bulk enrichment for large lists"
  },
  {
    "value": "Hard to qualify leads quickly",
    "label": "Hard to qualify leads quickly"
  },
  {
    "value": "Need faster data collection",
    "label": "Need faster data collection"
  },
  {
    "value": "Lead Quality",
    "label": "Lead Quality"
  },
  {
    "value": "Volume",
    "label": "Volume"
  }
];

const monthlyBudgetOptions = [
  {
    "value": "$3k+",
    "label": "$3k+"
  },
  {
    "value": "$1k–$3k",
    "label": "$1k–$3k"
  },
  {
    "value": "$250–$1k",
    "label": "$250–$1k"
  },
  {
    "value": "<$250",
    "label": "<$250"
  },
  {
    "value": "$1k - $3k",
    "label": "$1k - $3k"
  },
  {
    "value": "$3k - $5k",
    "label": "$3k - $5k"
  }
];

const priorityLevelOptions = [
  {
    "value": "High",
    "label": "High"
  },
  {
    "value": "Medium",
    "label": "Medium"
  },
  {
    "value": "Low",
    "label": "Low"
  }
];

const validationExpectationOptions = [
  {
    "value": "❌ Not sure",
    "label": "❌ Not sure"
  },
  {
    "value": "💰 Closed revenue required",
    "label": "💰 Closed revenue required"
  },
  {
    "value": "📊 Conversion over 30–60 days",
    "label": "📊 Conversion over 30–60 days"
  },
  {
    "value": "📈 Directional signal (reply / interest rate)",
    "label": "📈 Directional signal (reply / interest rate)"
  },
  {
    "value": "10 Verified Leads",
    "label": "10 Verified Leads"
  }
];

const leadOwnerOptions = [
  {
    "value": "❌ No dedicated owner yet",
    "label": "❌ No dedicated owner yet"
  },
  {
    "value": "🤖 Automation / outbound system (Deal Scale)",
    "label": "🤖 Automation / outbound system (Deal Scale)"
  },
  {
    "value": "👥 Sales rep / SDR",
    "label": "👥 Sales rep / SDR"
  },
  {
    "value": "👤 Founder",
    "label": "👤 Founder"
  },
  {
    "value": "Myself",
    "label": "Myself"
  }
];



// * Zod Schema
export const intakeFormSchema = z.object({
  name: z.string().min(2, "Name is required"),
  paidPilot: z.string().optional(),
  avgDealAmount: z.preprocess((val) => Number(val), z.number().optional()),
  businessType: z.array(z.string()).optional(),
  crmConnection: z.array(z.string()).optional(),
  website: z.string().optional(),
  conversionRate: z.preprocess((val) => Number(val), z.number().optional()),
  currentCrm: z.string().optional(),
  dealsPerMonth: z.preprocess((val) => Number(val), z.number().optional()),
  icpDescription: z.string().optional(),
  scrapingInstructions: z.string().optional(),
  email: z.string().email("Invalid email address"),
  existingLeadLists: z.array(z.string()).optional(),
  highIntentSources: z.string().optional(),
  icpCategory: z.array(z.string()).optional(),
  speed: z.string().optional(),
  interestedFeatures: z.array(z.string()).optional(),
  leadVolumePerMonth: z.preprocess((val) => Number(val), z.number().optional()),
  painPoints: z.array(z.string()).optional(),
  monthlyBudget: z.string().optional(),
  notes: z.string().optional(),
  phone: z.string().optional(),
  priorityLevel: z.array(z.string()).optional(),
  kickoffDate: z.string().optional(),
  startDate: z.string().optional(),
  validationExpectation: z.string().optional(),
  leadOwner: z.string().optional(),

});

export type IntakeFormValues = z.infer<typeof intakeFormSchema>;

// * Field Configurations
export const intakeFormFields: FieldConfig[] = [
  {
    name: "name",
    label: " Name",
    type: "text",
    placeholder: " Name...",
    value: "",
    onChange: () => {},
  },
  {
    name: "paidPilot",
    label: "Are you willing to pay for a small pilot to validate lead quality before scaling",
    type: "select",
    placeholder: "Are you willing to pay for a small pilot to validate lead quality before scaling...",
    value: "",
    onChange: () => {},
    options: paidPilotOptions,
  },
  {
    name: "avgDealAmount",
    label: "Avg Deal Amount ($)",
    type: "number",
    placeholder: "Avg Deal Amount ($)...",
    value: "",
    onChange: () => {},
  },
  {
    name: "businessType",
    label: "Business Type / Niche",
    type: "multiselect",
    placeholder: "Business Type / Niche...",
    value: [],
    onChange: () => {},
    options: businessTypeOptions,
  },
  {
    name: "crmConnection",
    label: "Can we connect directly to your CRM?",
    type: "multiselect",
    placeholder: "Can we connect directly to your CRM?...",
    value: [],
    onChange: () => {},
    options: crmConnectionOptions,
  },
  {
    name: "website",
    label: "Company Website ?",
    type: "url",
    placeholder: "Company Website ?...",
    value: "",
    onChange: () => {},
  },
  {
    name: "conversionRate",
    label: "Conversion Rate %",
    type: "number",
    placeholder: "Conversion Rate %...",
    value: "",
    onChange: () => {},
  },
  {
    name: "currentCrm",
    label: "Current CRM",
    type: "text",
    placeholder: "Current CRM...",
    value: "",
    onChange: () => {},
  },
  {
    name: "dealsPerMonth",
    label: "Deals / Month",
    type: "number",
    placeholder: "Deals / Month...",
    value: "",
    onChange: () => {},
  },
  {
    name: "icpDescription",
    label: "Describe Your Ideal Customer Profile",
    type: "text",
    placeholder: "Describe Your Ideal Customer Profile...",
    value: "",
    onChange: () => {},
  },
  {
    name: "scrapingInstructions",
    label: "Detailed Scraping Instructions ?",
    type: "text",
    placeholder: "Detailed Scraping Instructions ?...",
    value: "",
    onChange: () => {},
  },
  {
    name: "email",
    label: "Email",
    type: "text",
    placeholder: "Email...",
    value: "",
    onChange: () => {},
  },
  {
    name: "existingLeadLists",
    label: "Existing Lead Lists?",
    type: "multiselect",
    placeholder: "Existing Lead Lists?...",
    value: [],
    onChange: () => {},
    options: existingLeadListsOptions,
  },
  {
    name: "highIntentSources",
    label: "High-Intent Lead Sources",
    type: "text",
    placeholder: "High-Intent Lead Sources...",
    value: "",
    onChange: () => {},
  },
  {
    name: "icpCategory",
    label: "ICP Category",
    type: "multiselect",
    placeholder: "ICP Category...",
    value: [],
    onChange: () => {},
    options: icpCategoryOptions,
  },
  {
    name: "speed",
    label: "If approved, how soon can you actively work and test a new lead list?",
    type: "select",
    placeholder: "If approved, how soon can you actively work and test a new lead list?...",
    value: "",
    onChange: () => {},
    options: speedOptions,
  },
  {
    name: "interestedFeatures",
    label: "Interested in these features?",
    type: "multiselect",
    placeholder: "Interested in these features?...",
    value: [],
    onChange: () => {},
    options: interestedFeaturesOptions,
  },
  {
    name: "leadVolumePerMonth",
    label: "Lead Volume / Month",
    type: "number",
    placeholder: "Lead Volume / Month...",
    value: "",
    onChange: () => {},
  },
  {
    name: "painPoints",
    label: "Main Pain Point(s)",
    type: "multiselect",
    placeholder: "Main Pain Point(s)...",
    value: [],
    onChange: () => {},
    options: painPointsOptions,
  },
  {
    name: "monthlyBudget",
    label: "Monthly Budget",
    type: "select",
    placeholder: "Monthly Budget...",
    value: "",
    onChange: () => {},
    options: monthlyBudgetOptions,
  },
  {
    name: "notes",
    label: "Notes",
    type: "text",
    placeholder: "Notes...",
    value: "",
    onChange: () => {},
  },
  {
    name: "phone",
    label: "Phone",
    type: "text",
    placeholder: "Phone...",
    value: "",
    onChange: () => {},
  },
  {
    name: "priorityLevel",
    label: "Priority Level",
    type: "multiselect",
    placeholder: "Priority Level...",
    value: [],
    onChange: () => {},
    options: priorityLevelOptions,
  },
  {
    name: "kickoffDate",
    label: "Schedule Kickoff Call",
    type: "date",
    placeholder: "Schedule Kickoff Call...",
    value: "",
    onChange: () => {},
  },
  {
    name: "startDate",
    label: "Start Date ",
    type: "date",
    placeholder: "Start Date ...",
    value: "",
    onChange: () => {},
  },
  {
    name: "validationExpectation",
    label: "What is your expectation for initial validation?",
    type: "select",
    placeholder: "What is your expectation for initial validation?...",
    value: "",
    onChange: () => {},
    options: validationExpectationOptions,
  },
  {
    name: "leadOwner",
    label: "Who will be responsible for reviewing and acting on the leads?",
    type: "select",
    placeholder: "Who will be responsible for reviewing and acting on the leads?...",
    value: "",
    onChange: () => {},
    options: leadOwnerOptions,
  },

];
